CPAN support - Fix broken tar command
jordansissel/fpm pull request #1940
Opened 2022-10-17 14:56 UTC by NicholasBHubbard

This PR fixes issue #1517 using the fix provided by #1518.

For handling CPAN tarballs with leading "./Foo/" directory structures, we must employ a tar --transform regex instead of a tar --strip-components command.

This bug can be reproduced by running the following command on the main branch:
```
fpm --no-cpan-test --cpan-verbose --verbose --debug-workspace --workdir $HOME/tmp -t rpm -s cpan -v 0.010000 Alien::astyle
```

2022-10-22 01:13 UTC, wbraswell commented
@jordansissel 
As with the other Perl-related code, I have personally reviewed this pull request and I approve it.  Please approve and merge, thanks!

2022-10-25 18:19 UTC, wbraswell commented
Ping @jordansissel

2022-10-25 18:40 UTC, jordansissel commented
I haven’t been at a desk much this week, so I haven’t been able to review this PR.

On Tue, Oct 25, 2022, at 11:19 AM, William N. Braswell, Jr. wrote:
> 
> 
> Ping @jordansissel <https://github.com/jordansissel>
> 
> 
> —
> Reply to this email directly, view it on GitHub <https://github.com/jordansissel/fpm/pull/1940#issuecomment-1290966562>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AABAF2VZT7ILLBINQHYHMU3WFAQDRANCNFSM6AAAAAARHFCOX4>.
> You are receiving this because you were mentioned.Message ID: ***@***.***>
>

2022-10-26 06:02 UTC, jordansissel requested changes
Thanks for working on this!

This new test takes a pretty long time on my workstation. I tried timing it, but my attempt errored after 4 minutes because my test container was missing `g++` -- it surely would have taken more time if I had that dependency.

Are there any other ways we can try test this that might be faster? It also adds additional external dependencies (g++, etc) which adds additional maintenance burdens to the test suite.

One thought is that we could test the `unpack` method directly. This method has `private` access, but we can still invoke it in Ruby using `instance_eval`, like this:

```
directory = subject.instance_eval { unpack("my.tar.gz") }

# The 'directory' variable is a string with the path to where the module was unpacked.
# Now we can list things in that directory and verify the paths are as expected.
```

If we include a .tar.gz in this test as a fixture with a known directory structure, specifically the relative `./foo/bar` style paths, it could be tested without reaching out to the internet, without adding a dependency, and much faster.

Here's an example I came up with to test -- 

```
# Create a tarball with a file './foo/bar'
$ mkdir -p /tmp/z/foo
$ touch $_/bar
$ tar -C /tmp/z -cvzf hello.tar.gz .
./
./foo/
./foo/bar

$ bundle exec irb
...
irb(main):003:0> directory = subject.instance_eval { unpack("hello.tar.gz") }
=> "/tmp/package-cpan-build-c133f629e51c353b598c8924fe88767b6407896f2fa875e41b3eb2a58a7c/module"
```

The above shows how we can invoke `unpack` directly, and we can use other tools like ruby's `Find.find` method or similar to make assertions about the structure and contents of the unpacked tarball.

What do you think?

2022-10-28 22:07 UTC, NicholasBHubbard commented
Thanks for the idea @jordansissel! I used the example code you gave me to create a test that shows that cpan.rb's unpack method can handle tarballs containing `./` leading paths. Let me know what you think.

2022-10-28 23:06 UTC, jordansissel commented
Nice! Much faster.

```
% bundle exec rspec spec/fpm/package/cpan_spec.rb
....

Finished in 11.32 seconds (files took 0.20792 seconds to load)
4 examples, 0 failures
```

2022-10-28 23:06 UTC, merged

2022-10-29 00:31 UTC, wbraswell commented
Thanks @jordansissel !  :-)